// Code generated by "stringer -type=Mnemonic"; DO NOT EDIT.

package jump

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-0]
	_ = x[JGT-1]
	_ = x[JEQ-2]
	_ = x[JGE-3]
	_ = x[JLT-4]
	_ = x[JNE-5]
	_ = x[JLE-6]
	_ = x[JMP-7]
	_ = x[Unknown-8]
}

const _Mnemonic_name = "NullJGTJEQJGEJLTJNEJLEJMPUnknown"

var _Mnemonic_index = [...]uint8{0, 4, 7, 10, 13, 16, 19, 22, 25, 32}

func (i Mnemonic) String() string {
	if i < 0 || i >= Mnemonic(len(_Mnemonic_index)-1) {
		return "Mnemonic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mnemonic_name[_Mnemonic_index[i]:_Mnemonic_index[i+1]]
}
