// Code generated by "stringer -type=Type"; DO NOT EDIT.

package command

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[C-1]
	_ = x[L-2]
	_ = x[Unknown-3]
}

const _Type_name = "ACLUnknown"

var _Type_index = [...]uint8{0, 1, 2, 3, 10}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
