// Code generated by "stringer -type=Mnemonic"; DO NOT EDIT.

package dest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-0]
	_ = x[M-1]
	_ = x[D-2]
	_ = x[MD-3]
	_ = x[A-4]
	_ = x[AM-5]
	_ = x[AD-6]
	_ = x[AMD-7]
	_ = x[Unknown-8]
}

const _Mnemonic_name = "NullMDMDAAMADAMDUnknown"

var _Mnemonic_index = [...]uint8{0, 4, 5, 6, 8, 9, 11, 13, 16, 23}

func (i Mnemonic) String() string {
	if i < 0 || i >= Mnemonic(len(_Mnemonic_index)-1) {
		return "Mnemonic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mnemonic_name[_Mnemonic_index[i]:_Mnemonic_index[i+1]]
}
